/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v2CourseMarketSol from "./v2-CourseMarket.sol";
export type { v2CourseMarketSol };
export type { CourseCertificate } from "./CourseCertificate";
export type { LaoyuanERC721Coin } from "./LaoyuanERC721Coin";
export type { TechArticleDAO } from "./TechArticleDAO";
export type { YiDengToken } from "./YiDengToken";
export type { UpgradeYiDengToken } from "./UpgradeYiDengToken";
export type { UpgradeYiDengTokenV2 } from "./UpgradeYiDengTokenV2";
