/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v2CourseMarketSol from "./v2-CourseMarket.sol";
export type { v2CourseMarketSol };
export type { YiDengToken } from "./YiDengToken";
