/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as v2CourseMarketSol from "./v2-CourseMarket.sol";
export { YiDengToken__factory } from "./YiDengToken__factory";
